128 paginate freaks
Agilefreaks/FreaksCatalog-API pull request #12
Opened 2021-08-03 12:24 UTC by salcudeann

## Description
In this PR i've implemented cursor pagination and i've created a test for this.

## Related
[[42] Paginate Freaks](https://trello.com/c/FSj8oGU7/128-paginate-freaks)

## Steps to Test or Reproduce
Simple, just run the test from _freak_pagination_spec.rb_. Path: _spec/controllers/graphql/queries/freaks_pagination_spec.rb_.

2021-08-03 13:39 UTC, alex-damian-negru requested changes

2021-08-03 13:39 UTC, alex-damian-negru commented on spec/fixtures/responses/queries/Freaks/default.json
> +    "errors": [
This is not the expected response.

2021-08-04 09:20 UTC, alex-damian-negru approved these changes
Seems legit :+1:

2021-08-04 11:28 UTC, salcudeann commented
![](https://github.trello.services/images/mini-trello-icon.png) [Paginate Freaks](https://trello.com/c/FSj8oGU7/128-paginate-freaks)

2021-08-04 11:28 UTC, salcudeann commented
![](https://github.trello.services/images/mini-trello-icon.png) [Paginate Freaks](https://trello.com/c/FSj8oGU7/128-paginate-freaks)

2021-08-04 11:29 UTC, merged