[121] Add projects to a freak
Agilefreaks/FreaksCatalog-API pull request #21
Opened 2021-08-11 11:54 UTC by salcudeann

## Description

## Related

[[42] Add Projects to Freak](https://trello.com/c/RQBdanH4/121-add-projects-to-freak)

## Steps to Test or Reproduce

~To be resolved~

2021-08-16 09:23 UTC, alex-damian-negru requested changes

2021-08-16 09:23 UTC, alex-damian-negru commented on app/models/freak.rb
> +  has_many :projects, as: :proj, dependent: nil
Please avoid incomplete terms (e.g. `proj`) as they can be unclear. I don't think the `as` or `dependent` options are needed here either.

2021-08-16 09:23 UTC, alex-damian-negru commented on app/models/project.rb
> +  belongs_to :proj, polymorphic: true
Why is this polymorphic & referencing itself? o_O

2021-08-16 09:23 UTC, alex-damian-negru commented on db/migrate/20210802074146_create_freaks.rb
> +      t.string :email
Avoid changing old migrations. All new DB changes should happen in new migrations.

That aside, why rename this to `email`?

2021-08-16 09:23 UTC, alex-damian-negru commented on db/migrate/20210811084757_create_projects.rb
> +      t.references :proj, polymorphic: true
What's the purpose behind this?

2021-08-19 07:16 UTC, alex-damian-negru commented
@salcudeann please rebase this.

2021-08-19 11:50 UTC, salcudeann commented
> @salcudeann please rebase this.

I think i should close thir PR and create a new one. I started with some mistakes and i think it would be better if i make a new branch for creating a project.

2021-08-23 08:11 UTC, closed without merging