[130] Add photo to a freak - FIX
Agilefreaks/FreaksCatalog-API pull request #28
Opened 2021-08-18 09:15 UTC by salcudeann

## Description
Fix issues that can be found in [this PR](https://github.com/Agilefreaks/FreaksCatalog-API/pull/23). 
Add a mutation to create a photo with next fields: imageableId, imageableType, uri. imageableType represents the type of object where is assigned this photo and the imageableId represents the id of the object.

## Related

[[42] Add photo to a freak](https://trello.com/c/0yKfo1ER/130-add-photo-to-a-freak)

## Steps to Test or Reproduce
Create a photo entry with next GraphQl mutation:
```GraphQlmutation {
  photoCreate(imageableId: 1, imageableType:"Freak", uri: "https://www.gravatar.com/avatar/00000000000000000000000000000000") {
    imageableId
    uri
  }
}
```

2021-08-18 12:55 UTC, gabrielgiroe1 commented
Please resolve warnings from guard

2021-08-18 13:10 UTC, gabrielgiroe1 commented
Please put Guardfile in gitignore

2021-08-18 13:42 UTC, gabrielgiroe1 approved these changes

2021-08-19 06:34 UTC, pirvudoru commented on app/graphql/types/freak_type.rb
> +    field :photo, PhotoType, null: true
This is considered a breaking change :)

2021-08-19 06:34 UTC, pirvudoru commented on app/graphql/types/url.rb
> +      return url if url.is_a?(URI::HTTP) || url.is_a?(URI::HTTPS)
You don't need `return`

2021-08-19 06:34 UTC, pirvudoru commented on spec/controllers/graphql/mutations/photo_create_spec.rb
> +    it { is_expected.to match_response_for(mutation: :photo_create, sample: :photoCreate) }
please use snake_case

2021-08-19 06:34 UTC, pirvudoru commented on spec/fixtures/requests/mutations/photo_create.graphql
> +    photoCreate(imageableId: 1, imageableType:"Freak", uri: "https://www.gravatar.com/avatar/00000000000000000000000000000000") {
So we don't care if the imageableType+imageableId actually exist in the database.

2021-08-19 06:46 UTC, alex-damian-negru requested changes

2021-08-19 06:46 UTC, alex-damian-negru commented on app/graphql/types/photo_type.rb
> +    field :imageable_id, String, null: false
This should be of the same type as the mutation argument
```ruby
argument :imageable_id, GraphQL::Types::ID, required: true
```

2021-08-19 06:46 UTC, alex-damian-negru commented on app/graphql/types/photo_type.rb
> +    field :imageable_id, String, null: false
Also, how can one know the possible values for `imageable_type`? :)

2021-08-19 06:48 UTC, alex-damian-negru commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Photo to a Freak](https://trello.com/c/0yKfo1ER/130-add-photo-to-a-freak)

2021-08-19 11:22 UTC, alex-damian-negru requested changes

2021-08-19 11:22 UTC, alex-damian-negru commented on app/graphql/resolvers/photo_create_resolver.rb
> +    argument :imageable_type, String, required: true
This is not a descripton. Look over https://graphql-ruby.org/fields/introduction.html#field-documentation

2021-08-19 12:08 UTC, salcudeann commented on app/graphql/resolvers/photo_create_resolver.rb
> +    argument :imageable_type, String, required: true
Done :+1:

2021-08-20 06:09 UTC, pirvudoru commented on app/graphql/resolvers/photo_create_resolver.rb
> +    argument :uri, Types::Url, required: true
We will need to add validations for these arguments. Currently someone can add anything in the fields. Ticket for another time.

2021-08-20 06:09 UTC, merged