[120] Add technologies to a freak
Agilefreaks/FreaksCatalog-API pull request #29
Opened 2021-08-20 12:20 UTC by salcudeann

## Description
Create a Technology model with `name` and `description` properties and a database table named `technologies` for this model.
Create a association between Freak and Technology and a database table for this association named `freak_technologies` , with `id`, `freak_id` and `technology_id` columns, to help us make the association between these 2 models.
Also, the json data from technologies was removed,  now when we run the `freaks_spec` test a technology object is created in database and assigned for a freak (by adding an entry in `freak_technologies` table with `freak_id` and `technology_id` values) with the help of factories.

## Related

[[42] Add Technologies to a Freak ](https://trello.com/c/uCnM0Nrv/120-add-technologies-to-a-freak)

## Steps to Test or Reproduce

QUESTION for backend developers:
In `seeds.db` I've created a Technology entry in db and then a Freak entry with this technology associated. Is there a way to test this before merging this PR in main?

2021-08-20 12:22 UTC, salcudeann commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Technologies to a Freak](https://trello.com/c/uCnM0Nrv/120-add-technologies-to-a-freak)

2021-08-20 13:19 UTC, gabrielgiroe1 reviewed
Do you need technologies.json file?

2021-08-20 13:40 UTC, gabrielgiroe1 requested changes

2021-08-20 13:40 UTC, gabrielgiroe1 commented on db/seeds.rb
> +)
You need a test for seed data

2021-08-24 10:01 UTC, gabrielgiroe1 approved these changes

2021-08-25 08:50 UTC, alex-damian-negru approved these changes
Looks good. Check the comments below before merging.

2021-08-25 08:50 UTC, alex-damian-negru commented on .rubocop.yml
> +
Some blank lines here.

2021-08-25 08:50 UTC, alex-damian-negru commented on spec/factories/technology.rb
> +    name { 'Ruby' }
Not a requirement, but if you wanna be sassy you can use `Faker::ProgrammingLanguage.name`

```ruby
Faker::ProgrammingLanguage.name #=> "Ruby"
```

2021-08-25 10:44 UTC, merged