[81] Setup Rubocop & Reek
Agilefreaks/FreaksCatalog-API pull request #3
Opened 2021-07-26 11:53 UTC by salcudeann

2021-07-26 12:04 UTC, drqCode requested changes

2021-07-26 12:04 UTC, drqCode commented on rubocop_log.txt
> +  gem 'listen', '~> 3.3'
Add this file to gitignore. We don't want to track .log files

2021-07-26 13:13 UTC, drqCode approved these changes

2021-07-26 14:44 UTC, alex-damian-negru approved these changes

2021-07-27 07:40 UTC, merged

2021-07-27 11:06 UTC, gabrielgiroe1 commented
We need to do another PR in which we add [guard-rubocop](https://github.com/rubocop/guard-rubocop). CC: @salcudeann

2021-07-28 07:20 UTC, alex-damian-negru commented
![](https://github.trello.services/images/mini-trello-icon.png) [API: Enforce best practices and code style analyzer](https://trello.com/c/BWzpWcMS/81-api-enforce-best-practices-and-code-style-analyzer)