[115] Create Freak model and add Hard-coded data
Agilefreaks/FreaksCatalog-API pull request #7
Opened 2021-07-29 13:50 UTC by salcudeann

2021-07-29 14:00 UTC, alex-damian-negru submitted a review, later dismissed
How can I test this?

Please add a PR description from now on.

2021-07-29 14:15 UTC, alex-damian-negru commented
![](https://github.trello.services/images/mini-trello-icon.png) [Get hardcoded Freaks](https://trello.com/c/en8qlw3c/115-get-hardcoded-freaks)

2021-08-02 07:38 UTC, pirvudoru approved these changes

2021-08-02 07:52 UTC, pirvudoru requested changes

2021-08-02 07:52 UTC, pirvudoru commented on app/graphql/models/level.rb
> +module Models
This module should be named "Types"

2021-08-02 07:52 UTC, pirvudoru commented on tatus
> +[33mcommit 758be0ccab28ce82cda6593a763e253cf3c6999d[m
What's this file about ? :) I assume we can delete it.

2021-08-02 07:52 UTC, pirvudoru commented on app/graphql/models/level.rb
> +module Models
Here you got it right: 
https://github.com/Agilefreaks/FreaksCatalog-API/pull/7/files#diff-eb9a313cd462df6ec80d88d35d2eae1fddcd38136099d37d431738e500a350e0R4

All other Models:: should follow the same pattern. See how you are inheriting from `Types::BaseObject`

2021-08-02 11:06 UTC, pirvudoru approved these changes
:100:

2021-08-02 11:07 UTC, merged